.\"
.\"  QSapecNG - Qt based SapecNG GUI front-end
.\"  Copyright (C) 2009-2010 Michele Caini
.\"
.\"  This program is free software: you can redistribute it and/or modify
.\"  it under the terms of the GNU General Public License as published by
.\"  the Free Software Foundation, either version 3 of the License, or
.\"  (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\"
.\" process with groff -man -Tascii qsapecng.1
.\" or with groff -t -e -mandoc -Tps qsapecng.1 > qsapecng.ps
.\" or with nroff -man qsapecng.1 | less

.TH QSAPECNG 1 "2010-11-14" "GNU GPLv3" "Program Description"
.SH NAME
qsapecng \- symbolic analyzer of linear analog circuits
.SH SYNOPSIS
.SY qsapecng
.YS
.SH DESCRIPTION
QSapecNG is a Qt-based program for symbolic analysis of linear analog circuits.
In fact, it consists of two indipendent parts: the SapecNG framework engine
and the application gui QSapecNG.

It is an open source, multi-platform project, continuously enhanced by students
and researchers of the Department of Electronics and Telecommunications (DET) of
the University of Florence. It comes as continuation of SapWin for Windows, in
order to give to the project a full compatibility on other platforms.

Through QSapecNG users can draw, solve and analyze analog circuits as well as
manage them.

QSapecNG is freely available on SourceForge
.UR https://sourceforge.net/projects/qsapecng/
.UE .

A previous version of SapecNG is available too, on SourceForge
.UR https://sourceforge.net/projects/sapec-ng/
.UE .
Pre-compiled packages will be also available from projects related pages.
.SH USAGE
TODO
.SH COPYRIGHT
Copyright (C) 2009-2010
.MT michele.caini@gmail.com
Michele Caini
.ME

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY.
.SH "THANKS TO"
QSapecNG is based in part on the work of the
.UR http://qwt.sf.net
Qwt Project
.UE

Project coordinators are:
.IP - 2
Prof. S. Manetti (who developed last version of SapWin)
.IP - 2
.MT luchetta@unifi.it
Prof. A. Luchetta
.ME
.P
Debian packager and maintainer is
.MT simros85@gmail.com
S. Rossetto
.ME
